# Generated by Django 4.0.4 on 2022-10-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='domestico',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='animal',
            name='nome_animal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='animal',
            name='predador',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='animal',
            name='venenoso',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
